name: install_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: chimp
          environment-file: chimp_cpu.yml
          mamba-version: "*"
          auto-activate-base: false
      - name: Install dependencies
        run: |
            pip install pytest pytest-cov
            pip install -e .
      - name: Run tests with pytest
        run: |
            python -m pytest --cov=pytorch_retrieve test/data/ --durations=0 -m "not slow"
